### ISSUE TITLE
Obstacle too close to the area bound can lead to wrong path

### ISSUE THREAD

**Issue by alexvaut** [ClemensElflein/open_mower_ros#63] opened 2023-09-05 20:53 UTC
I have an example where an obstacle is close to the area bound. It makes the polygon of the first outline to be split. It could be fine, but the assumption is that n outlines (by default n=4) beginning and end are close to each other so they can form a unique path. This assumption is wrong (I believe).

Here is the 4th outline which is cut into 3 pieces (a long one and the 2 highlighted):
![image](https://github.com/ClemensElflein/open_mower_ros/assets/20702322/fa0e0fcb-3207-4803-a7c8-f305e09d4010)

And here you can see when the 2 are finished, it goes straight to the next outline (the second), the beginning of this one is too far way:
![image](https://github.com/ClemensElflein/open_mower_ros/assets/20702322/20da5972-3a14-422d-9ed1-bbb4213e0920)

It passes outside of the authorized navigation area.

From my point of view, the issue is in function planPath of coverage_planner.cpp but I don't know exactly, having unit tests would help...

**Comment by alexvaut** [comment] 2023-09-07 06:43
Visualization of the fix:
![image](https://github.com/ClemensElflein/open_mower_ros/assets/20702322/1c5989bb-dbcf-40fc-b79f-ae94157232ec)

**Comment by TomasSeven** [comment] 2023-10-27 12:04
this fix is working for me

**Comment by karlranseierausrom** [comment] 2024-04-19 16:25
I have no idea of the source-code of Slic3r and I am more comfortable with graphical programming. It will be really hard for me to understand the code. But: For me it sounds like the problem is somewhere else, but not in the slic3r. Why is it rotating when it changes to navigation? In 3D printing it makes sense to distinguish between printing and moving, but here every move can be mowing. So maybe it is solved, if the navigation is redefined as mowing? Anyway I had examples with hand drawn rectangles, where at one path the mowing motor was switches off. There were only 3 straight lines mowing, and one line was not shown, but the mower drove it with slow mowing motor.

**Comment by ClemensElflein** [comment] 2024-04-24 17:27
@karlranseierausrom since the mower cannot move sideways, on tight turns it needs to rotate on spot. It has nothing to do with mowing vs not mowing.

I.e. if you are driving the outline as a spiral, it will be one continuous motion, but if you do like two tight 90 degree turns between the lines, the mower will rotate in place, because it cannot just shift sideways like that. During polygon grouping, we can make sure that there are no such small 90 degree turns in there in order to avoid this behavior.

**Comment by ClemensElflein** [comment] 2024-04-24 18:28
should be fixed in main, please test and report back. If anyone has map.bag files to test, feel free to share (e.g. discord or link here).

**Comment by 11phc** [comment] 2024-04-25 14:11
That is looking much better, thank you.  So do you think you have fixed it now in the slicer / router planner?  
Or are my maps a bit "corrupted" from the start (because of my alternative way of creating them in arcgis and exporting to GPX etc.) and you did it instead by modifying my maps?

**Comment by ClemensElflein** [comment] 2024-04-25 19:31
Code changes only, I did not touch the maps

**Comment by karlranseierausrom** [comment] 2024-04-25 20:03
> @karlranseierausrom since the mower cannot move sideways, on tight turns it needs to rotate on spot. It has nothing to do with mowing vs not mowing.

Looks like I didn't understand the problem. I observed some weird 270° and -270° moves at some point. I thought you were talking abut them.

Is a json file useful, too? Do you want another? I deleted the area and will rewrite it on the weekend.

Thanks for all your work!

**Comment by jludo1** [comment] 2024-04-27 08:53
currently in edge version (I have just completely redone the SD card)

my mower always tries to cross my obstacles I attach a screenshot of the GUI interface

I share with you by map.bag on (post@x-tech.online)

thank you for your work on this project
![map](https://github.com/ClemensElflein/open_mower_ros/assets/164685659/b1c9ca53-2dbc-4596-a6f9-110c724c1f94)

**Comment by ClemensElflein** [comment] 2024-04-27 12:50
This looks like an edited map with sparse points which is known to break the path planning algorithm

**Comment by jludo1** [comment] 2024-04-27 13:01
I drew the map from the gui interface (https://github.com/cedbossneo/openmower-gui)
the problem and maybe due to that?

Is there a way to modify the map and correct this?

**Comment by ClemensElflein** [comment] 2024-04-27 19:51
Yes, the edited maps are known to cause issues. I did not look into the map editors too much, so I can't really help with this. Best would be to just record the map instead of creating it in the UI. If you have questions regarding map editing, you can try asking on Discord or in the GUI repo, I know that some people do it successfully.

I'm closing this for now, since it is reported fixed by some people.

**Closed by ClemensElflein** 2024-04-27 19:51 UTC
